# Generated by Django 5.1.6 on 2026-04-22 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='channel',
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='DeviceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.contact')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.device')),
            ],
        ),
    ]
