# Generated by Django 5.1.6 on 2026-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_contact_channel_alter_log_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_down_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_status',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=10),
        ),
    ]
