# Generated by Django 5.1.6 on 2026-05-06 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_log_message_service_last_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=10)),
                ('notification_type', models.CharField(choices=[('SERVICE_DOWN', 'Service Down'), ('SERVICE_RECOVER', 'Service Recover'), ('DEVICE_OFFLINE', 'Device Offline'), ('DEVICE_ONLINE', 'Device Online'), ('THRESHOLD_WARNING', 'Threshold Warning')], max_length=20)),
                ('recipient', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notification_channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('BOTH', 'WhatsApp & Email')], default='WHATSAPP', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='has_power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_config_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='down_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_down_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='notification_cooldown_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='uptime_percentage',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_down_reason',
            field=models.CharField(blank=True, choices=[('NETWORK_UNREACHABLE', 'Jaringan Down Total'), ('TIMEOUT', 'Request Timeout (Lemot)'), ('HTTP_400', 'Bad Request (400)'), ('HTTP_401', 'Unauthorized (401)'), ('HTTP_403', 'Forbidden (403)'), ('HTTP_404', 'Not Found (404)'), ('HTTP_500', 'Internal Server Error (500)'), ('HTTP_502', 'Bad Gateway (502)'), ('HTTP_503', 'Service Unavailable (503)'), ('HTTP_504', 'Gateway Timeout (504)'), ('CONNECTION_REFUSED', 'Koneksi Ditolak'), ('SSL_ERROR', 'SSL Certificate Error'), ('DNS_ERROR', 'DNS Resolution Failed'), ('UNKNOWN_ERROR', 'Unknown Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_status',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('DEGRADED', 'DEGRADED'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=10),
        ),
    ]
